server:
  port: 8011

spring:
  application:
    name: api-gateway
  config:
    import: optional:file:.env[.properties]
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # the easiest way to enable discovery routing is to to enable discovery locator.
          # If the client sent request using the service name in api spring cloud gateway will automatically route
          # request to the appropriate service
          lower-case-service-id: true # Enabling it allow you using microservice-name in lower case.
          # Eureka know (and show you) the service name by upper case like - 'USERS-WS'. Now 'USERS-WS'='users-ws'
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_DEFAULT_ZONE}

