spring:
  application:
    name: users-ws
  config:
    import: optional:file:.env[.properties]
  devtools:
    restart:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_DEFAULT_ZONE}
  instance:
    prefer-ip-address: true

server:
  port: 0 # setting port to '0' will give you dynamic port numbers.
          # It's important if you want to run multiple instances of this user-service
  servlet:
    context-path: /users-ws #NOTE: if you use context-path here then the api-gateway can't locate this app using only
    #appname which is 'USERS-WS' this - '<api-gateway-url>:<api-gateway-port>/USERS-WS/users/status/check' will not work
    #You have to add the context-path in the url to make it work.
