server:
  port: ${EUREKA_SERVER_PORT}

# Spring Configs
spring:
#  security:
#    user:
#      name: ${EUREKA_SERVER_USERNAME}
#      password: ${EUREKA_SERVER_PASSWORD}
  config:
    import: optional:file:.env[.properties]

eureka:
  dashboard:
    enabled: true
    path: ${EUREKA_SERVER_DASHBOARD}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_DEFAULT_ZONE}
