spring:
  application:
    name: 'user-account-managements-ws'
  config:
    import: optional:file:.env[.properties]
  devtools:
    restart:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_DEFAULT_ZONE}
  instance:
    prefer-ip-address: true

server:
  port: 0
  servlet:
    context-path: /user-account-managements-ws
